redis:
  image: redis
  ports:
    - "6379:6379"

app:
  build: .
  working_dir: /src
  restart: always
  links:
    - redis
  environment:
    - REDIS_HOST=redis://redis:6379/0
  volumes:
    - ./:/src
  ports:
    - "8000:8000"
  command: tail -F /dev/null
