# Generated by Django 2.1.7 on 2019-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_visit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
