# Generated by Django 2.1.7 on 2019-03-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0002_usersession_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
